
/*
========================================================
  PROJECT 3: SQL DATA ANALYSIS
  E-Commerce Order Fulfillment & Sales Analysis
========================================================
  Author        : Kingsley Ezenwanne
  Program       : DecodeLabs Industrial Training Kit
  Batch         : 2026
  Tool          : Microsoft SQL Server Management Studio (SSMS)
  Database      : DecodeLabs
  Source Data   : Dataset for Data Analytics (Cleaned)
--------------------------------------------------------
  Description:
  This script uses structured SQL queries to extract
  actionable business intelligence from 1,200 e-commerce
  orders. It covers SELECT, WHERE, GROUP BY, ORDER BY,
  HAVING, and CTEs to answer 10 stakeholder questions
  spanning revenue analysis, order status breakdown,
  coupon impact, and referral channel performance.
--------------------------------------------------------
  Key Clauses Demonstrated:
  SELECT, FROM, WHERE, GROUP BY, ORDER BY,
  HAVING, COUNT(), SUM(), AVG(), ROUND(), CTE (WITH)
========================================================
*/


-- Converts TotalPrice with many decimals to 2 decimal place
ALTER TABLE DecodeLabs
ALTER COLUMN TotalPrice DECIMAL(18, 2);

-- Convert UnitPrice with many decimals to 2 decimal place
ALTER TABLE DecodeLabs
ALTER COLUMN UnitPrice DECIMAL(18, 2);


-- 10 Stakeholder questions to answer with SQL queries:

-- Q1: What do the first 10 orders of the dataset look like?
SELECT TOP 10 *
FROM DecodeLabs;

-- Q2: Which orders had a TotalPrice above $3,000, and what products were they for?
SELECT * 
FROM DecodeLabs
WHERE TotalPrice > 3000
ORDER BY TotalPrice DESC;

-- Q3: How many orders were placed using the SAVE10 coupon code?
SELECT CouponCode,
	COUNT(*) AS OrderCount
FROM DecodeLabs
WHERE CouponCode = 'SAVE10'
GROUP BY CouponCode;

-- Q4: What is the total revenue and number of orders generated by each Product, ranked highest to lowest?
SELECT Product,
	SUM(TotalPrice) AS TotalRevenue,
	COUNT(*) AS OrderCount
FROM DecodeLabs
GROUP BY Product
ORDER BY TotalRevenue DESC;

-- Q5: What is the average order value (AOV) for each Payment Method?
SELECT PaymentMethod,
	AVG(TotalPrice) AS AOV
FROM DecodeLabs
GROUP BY PaymentMethod
ORDER BY AOV DESC;

-- Q6: How many orders fall under each Order Status category, and what is the total revenue associated with each?
SELECT OrderStatus,
	COUNT(*) AS TotalOrders,
	ROUND(SUM(TotalPrice), 2) AS TotalRevenue
FROM DecodeLabs
GROUP BY OrderStatus
ORDER BY TotalOrders DESC;

-- Q7: Which Referral Source brings in the highest average order value?
SELECT ReferralSource,
	ROUND(AVG(TotalPrice), 2) AS AOV
FROM DecodeLabs
GROUP BY ReferralSource
ORDER BY AOV DESC;

-- Q8: Among Delivered orders only, what is the total revenue contributed by each Product?
SELECT Product,
    ROUND(SUM(TotalPrice), 2) AS TotalRevenue
FROM DecodeLabs
WHERE OrderStatus = 'Delivered'
GROUP BY Product
ORDER BY TotalRevenue DESC;

-- Q9: For orders where a coupon was applied (i.e. CouponCode is not 'No Coupon'), what is the average TotalPrice per coupon type?
/* Note: '~No Coupon~' is the intentional label used to identify orders
where no coupon code was applied, imported as such from the cleaned dataset. */
SELECT CouponCode,
	ROUND(AVG(TotalPrice), 2) AS AvgOrderValue
FROM DecodeLabs
WHERE CouponCode != '~No Coupon~'
GROUP BY CouponCode;

-- Q10: Which products have generated more than $150,000 in total revenue?

-- Method 1: Using HAVING with the aggregate function directly
SELECT Product,
	SUM(TotalPrice) AS TotalRevenue
FROM DecodeLabs
GROUP BY Product
HAVING SUM(TotalPrice) > 150000;

-- Method 2: Using a Common Table Expression (CTE)
WITH cte AS (
SELECT Product,
	SUM(TotalPrice) AS TotalRevenue
FROM DecodeLabs
GROUP BY Product)
SELECT Product,
	TotalRevenue
FROM cte
WHERE TotalRevenue > 150000;


